### ISSUE TITLE
Flatpak packages no longer update

### ISSUE THREAD

**Issue by kemra102** [ublue-os/ublue-update#110] opened 2024-04-16 20:38 UTC
I noticed that on my uBlue Kinoite install that at some point last few months user installed flatpaks are no longer auto updated. I can't say when exactly because `flatpak history` only goes back as far as `Mar 26` and that is just showing new flatpaks I've installed. `journalctl` shows the following output with a very vague error:

```
Apr 16 20:48:34 fedora systemd[1]: Starting ublue-update.service - Universal Blue Update Oneshot Service...
Apr 16 20:48:36 fedora ublue-update[42890]: [2024-04-16 20:48:36,759] ublue_update.update_checks.system:INFO | System update available.
Apr 16 20:48:36 fedora ublue-update[42890]: [2024-04-16 20:48:36,760] ublue_update.update_inhibitors.hardware:INFO | System passed hardware checks
Apr 16 20:48:36 fedora ublue-update[42890]: [2024-04-16 20:48:36,760] ublue_update.cli:INFO | System passed all update checks
Apr 16 20:48:36 fedora sudo[42930]:     root : PWD=/ ; USER=kemra102 ; ENV=DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus ; COMMAND=/usr/>
Apr 16 20:52:55 fedora systemd[1]: ublue-update.service: Main process exited, code=exited, status=1/FAILURE
Apr 16 20:52:55 fedora systemd[1]: ublue-update.service: Failed with result 'exit-code'.
Apr 16 20:52:55 fedora systemd[1]: Failed to start ublue-update.service - Universal Blue Update Oneshot Service.
Apr 16 20:52:55 fedora systemd[1]: ublue-update.service: Consumed 2.495s CPU time.
```

Nothing obvious & AFAICT `ublue-update` doesn't log anywhere else so I'm not sure where to look next for information that may help in tracking down the issue.

**Comment by gerblesh** [comment] 2024-05-29 02:56
is this resolved? Can you try running `ublue-update` manually with `pkexec ublue-update`?

**Comment by gerblesh** [comment] 2024-05-29 02:58
might need to add some more logs to `ublue-update` been a while since I've touched this project

**Comment by kemra102** [comment] 2024-05-29 09:38
Hi @gerblesh - Yes this is still an issue. here is the output you requested:

```sh
❯ pkexec ublue-update
[2024-05-29 10:35:00,000] ublue_update.update_checks.system:INFO | No system update available.
[2024-05-29 10:35:00,002] ublue_update.update_inhibitors.hardware:INFO | System passed hardware checks
[2024-05-29 10:35:00,002] ublue_update.cli:INFO | System passed all update checks
topgrade returned code 1, program output:
―― 10:35:00 - System update ――
Pulling manifest: ostree-image-signed:docker://ghcr.io/kemra102/tourmaline:latest
No upgrade available.
―― 10:35:01 - Toolbx ――
―― 10:35:01 - Distrobox ――
―― 10:35:01 - Firmware upgrades ――
Devices with no available firmware updates: 
 • SSD 970 EVO Plus 2TB
 • System Firmware
 • Unifying Receiver
Devices with the latest available firmware version:
 • UEFI dbx
―― 10:35:01 - Flatpak User Packages ――
Looking for updates…

Nothing to do.
―― 10:35:01 - Flatpak System Packages ――
Looking for updates…

Nothing to do.
―― 10:35:01 - yadm ――
yadm failed: 
   0: Command failed: `/usr/bin/yadm pull`
   1: `/usr/bin/yadm` failed: exit status: 1

Location:
   src/steps/os/unix.rs:528―― 10:35:02 - pip3 ――
Requirement already satisfied: pip in /root/.local/lib/python3.12/site-packages (24.0)
―― 10:35:03 - Containers ――
―― 10:35:03 - Summary ――
System update: OK
config-update: OK
toolbx: OK
distrobox: OK
Firmware upgrades: OK
Flatpak: OK
yadm: FAILED
pip3: OK
Containers: OK
```

This seems to claim that my flatpaks are up to date but as you can see from this command that really isn't the case:

```sh
❯ flatpak update
Looking for updates…


        ID                                                    Branch                   Op             Remote              Download
 1.     fr.handbrake.ghb.Locale                               stable                   u              flathub             < 487.2 kB (partial)
 2.     it.mijorus.gearlever.Locale                           stable                   u              flathub              < 32.1 kB (partial)
 3.     org.chromium.Chromium.Codecs                          stable                   u              flathub             < 959.9 kB
 4.     org.chromium.Chromium.Locale                          stable                   u              flathub             < 184.7 kB (partial)
 5.     org.freedesktop.Platform.Compat.i386                  23.08                    u              flathub             < 109.4 MB
<---- snipped for brevity ---->
39.     org.mozilla.firefox                                   stable                   u              flathub              < 98.7 MB
40.     org.winehq.Wine.gecko                                 stable-23.08             u              flathub             < 108.6 MB
41.     org.winehq.Wine.mono                                  stable-23.08             u              flathub              < 83.5 MB

Proceed with these changes to the user installation? [Y/n]: n
```

**Comment by gerblesh** [comment] 2024-06-10 16:28
hmmm, this looks like something upstream with `topgrade` potentially? I'm not totally sure why it's skipping, does just running `topgrade --config /usr/share/ublue-update/topgrade-system.toml` work?

**Comment by kemra102** [comment] 2024-06-10 18:35
As requested:

```sh
❯ topgrade --config /usr/share/ublue-update/topgrade-system.toml

── 19:22:30 - System update ────────────────────────────────────────────────────
Pulling manifest: ostree-image-signed:docker://ghcr.io/kemra102/tourmaline:latest
Importing: ostree-image-signed:docker://ghcr.io/kemra102/tourmaline:latest (digest: sha256:9fa509e22cc3a98d398682a6e61f9e8e230379616c918c0fc8be9f12bfc653fd)
ostree chunk layers already present: 40
ostree chunk layers needed: 25 (823.8 MB)
custom layers already present: 1
custom layers needed: 8 (443.9 MB)
Fetching ostree chunk sha256:86e13570a99b (39.2 MB)... done
<---- snipped for brevity ---->
Fetching ostree chunk sha256:7de32ffb47c8 (8.6 MB)... done
Fetching layer sha256:80bae5ba9117 (290.5 MB)... done
<---- snipped for brevity ---->
Fetching layer sha256:6b6848fdf6b5 (647 bytes)... done
Staging deployment... done
Freed: 715.2 MB (pkgcache branches: 0)
Upgraded:
  fontconfig 2.15.0-4.fc40 -> 2.15.0-6.fc40
  mesa-dri-drivers 24.0.8-1.fc40 -> 24.0.9-1.fc40
  mesa-filesystem 24.0.8-1.fc40 -> 24.0.9-1.fc40
  mesa-libEGL 24.0.8-1.fc40 -> 24.0.9-1.fc40
  mesa-libGL 24.0.8-1.fc40 -> 24.0.9-1.fc40
  mesa-libgbm 24.0.8-1.fc40 -> 24.0.9-1.fc40
  mesa-libglapi 24.0.8-1.fc40 -> 24.0.9-1.fc40
  mesa-va-drivers-freeworld 24.0.8-1.fc40 -> 24.0.9-1.fc40
  mesa-vulkan-drivers 24.0.8-1.fc40 -> 24.0.9-1.fc40
  xdg-desktop-portal-kde 6.0.5-1.fc40 -> 6.0.5-2.fc40
Added:
  kf6-kimageformats-6.3.0-1.fc40.x86_64
  qt6-qtimageformats-6.7.1-1.fc40.x86_64
Run "systemctl reboot" to start a reboot

── 19:28:25 - Flatpak User Packages ────────────────────────────────────────────
Looking for updates…


        ID                                                    Branch                  Op             Remote             Download
 1. [✓] org.freedesktop.Platform.Compat.i386                  23.08                   u              flathub              2.5 MB / 109.4 MB
 2. [✓] org.freedesktop.Platform.GL.default                   23.08                   u              flathub             27.2 MB / 172.2 MB
 3. [✓] org.freedesktop.Platform.GL.default                   23.08-extra             u              flathub             14.0 MB / 172.2 MB
 4. [✓] org.freedesktop.Platform.GL32.default                 23.08                   u              flathub             30.5 MB / 184.2 MB
 5. [✓] org.freedesktop.Platform.GL32.default                 23.08-extra             u              flathub             13.1 MB / 184.2 MB
 6. [✓] org.freedesktop.Platform.Locale                       23.08                   u              flathub             17.8 kB / 360.2 MB
 7. [✓] org.freedesktop.Platform.VAAPI.Intel.i386             23.08                   u              flathub              2.9 kB / 1.9 MB
 8. [✓] org.freedesktop.Platform.VAAPI.Intel                  23.08                   u              flathub              2.9 kB / 13.4 MB
 9. [✓] org.freedesktop.Platform.ffmpeg-full                  23.08                   u              flathub            289.3 kB / 9.2 MB
10. [✓] org.freedesktop.Platform.ffmpeg_full.i386             23.08                   u              flathub            284.7 kB / 9.4 MB
11. [✓] org.freedesktop.Platform                              23.08                   u              flathub              3.8 MB / 227.5 MB

Updates complete.

── 19:29:04 - Flatpak System Packages ──────────────────────────────────────────
Looking for updates…

Nothing to do.

── 19:29:04 - Summary ──────────────────────────────────────────────────────────
System update: OK
Flatpak: OK
```

```sh
❯ flatpak update
Looking for updates…

Nothing to do.
```

I feel like there should have been more updates than just a few SDKs etc... In fact taking a look at the `flatpak history` things may have started working again as normal, for example I did not manually update this app but it got updated none the less:

```sh
Jun  9 11:12:16 pull           com.discordapp.Discord                    stable       user         flathub
Jun  9 11:12:16 deploy update  com.discordapp.Discord                    stable       user         flathub
```

**Comment by gerblesh** [comment] 2024-08-26 05:35
unless there's something different I'm missing I'll close this as a duplicate of https://github.com/ublue-os/ublue-update/issues/113

**Closed by gerblesh** 2024-08-26 05:35 UTC
